USE flights
/*
DELETE FROM BOOKING
DELETE FROM FLIGHT
DELETE FROM AGENCY
*/
--INSERT INTO FLIGHT(FNUMBER) VALUES (2)
--INSERT INTO AGENCY(NAME, COUNTRY) VALUES ('GOJO', 'BG')

--INSERT INTO BOOKING (CODE, AGENCY, FLIGHT_NUMBER, PRICE) VALUES (2, 'GOJO', 2, 100)

SELECT * FROM BOOKING
SELECT * FROM FLIGHT
SELECT * FROM AGENCY

UPDATE BOOKING SET STATUS = 0

SELECT * FROM BOOKING
SELECT * FROM FLIGHT
SELECT * FROM AGENCY

