CREATE TRIGGER trigger_remove_pass
ON BOOKING
AFTER DELETE
AS
	UPDATE FLIGHT
	SET NUM_PASS -= 1
	WHERE FNUMBER IN (SELECT FLIGHT_NUMBER FROM deleted)

	UPDATE AGENCY
	SET NUM_BOOK -=1 
	WHERE NAME IN (SELECT AGENCY FROM deleted)