CREATE TRIGGER trigger_update_bookings ON BOOKING
AFTER UPDATE
AS
IF UPDATE(STATUS)
	UPDATE FLIGHT
	SET NUM_PASS += 1
	WHERE FNUMBER IN (SELECT FLIGHT_NUMBER FROM inserted WHERE STATUS=1)

	UPDATE FLIGHT
	SET NUM_PASS -= 1
	WHERE FNUMBER IN (SELECT FLIGHT_NUMBER FROM inserted WHERE STATUS=0)

	UPDATE AGENCY
	SET NUM_BOOK += 1
	WHERE NAME IN (SELECT AGENCY FROM inserted WHERE STATUS=1)
	
	UPDATE AGENCY
	SET NUM_BOOK -= 1
	WHERE NAME IN (SELECT AGENCY FROM inserted WHERE STATUS=0)

