use flights

ALTER TABLE BOOKING
ADD CONSTRAINT pk_booking
PRIMARY KEY(CODE)

ALTER TABLE AIRLINE
ADD CONSTRAINT pk_airline
PRIMARY KEY(CODE)

ALTER TABLE AIRPLANE
ADD CONSTRAINT pk_airplane
PRIMARY KEY(CODE)

ALTER TABLE AGENCY
ADD CONSTRAINT pk_agency
PRIMARY KEY(NAME)

ALTER TABLE CUSTOMER
ADD CONSTRAINT pk_customer
PRIMARY KEY(ID)

ALTER TABLE AIRPORT
ADD CONSTRAINT pk_airport
PRIMARY KEY(CODE)

ALTER TABLE FLIGHT
ADD CONSTRAINT pk_flight
PRIMARY KEY(FNUMBER)

ALTER TABLE BOOKING
ADD CONSTRAINT fk_booking_airline
FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINE(CODE)


ALTER TABLE BOOKING
ADD FOREIGN KEY(AGENCY) REFERENCES AGENCY(NAME)


ALTER TABLE BOOKING
ADD FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FNUMBER)


ALTER TABLE BOOKING 
ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID) 

ALTER TABLE BOOKING
ALTER COLUMN PRICE DECIMAL(6,2) NOT NULL

ALTER TABLE AIRLINE
ADD UNIQUE(NAME)


--TEST
SELECT * FROM AIRLINE
INSERT INTO AIRLINE(CODE, NAME) VALUES (1, 'GOGO'), (2, 'GOGO')


ALTER TABLE AIRPORT
--TEST
ADD UNIQUE (NAME,COUNTRY)
INSERT INTO AIRPORT(CODE, NAME, COUNTRY) VALUES (1, 'GOGO', 'JOJO'), (2, 'GOGO', 'JOJO')


ALTER TABLE AIRPLANE
ADD CHECK (SEATS > 0)
--TEST
INSERT INTO AIRPLANE(AIRPLANE.CODE, SEATS) VALUES (1, 0)


ALTER TABLE BOOKING
ADD CHECK (FLIGHT_DATE >= BOOKING_DATE)

--test
INSERT INTO BOOKING(CODE, FLIGHT_DATE, BOOKING_DATE, PRICE) VALUES (1, '2019-06-06', '2019-07-06', 150)


ALTER TABLE CUSTOMER
ADD CONSTRAINT customer_valid_email_@
CHECK (EMAIL LIKE '%@%')

ALTER TABLE CUSTOMER
ADD CONSTRAINT customer_valid_email_point
CHECK (EMAIL LIKE '%.%')

ALTER TABLE CUSTOMER
ADD CONSTRAINT customer_valid_email_length
CHECK (LEN(EMAIL) >= 6)

--test
INSERT INTO CUSTOMER (ID, EMAIL) VALUES (2, 'gog@.') 

ALTER TABLE BOOKING
ADD CONSTRAINT booking_status
CHECK (STATUS IN(0,1))

--INSERT INTO BOOKING(CODE, STATUS, PRICE) VALUES (3, 2, 15)
--INSERT INTO BOOKING(CODE, STATUS, PRICE) VALUES (3, 1, 15)
--select * from booking

/*
drop table BOOKING
drop table AIRLINE
drop table AGENCY
drop table AIRPLANE
drop table AIRPORT
drop table CUSTOMER
drop table FLIGHT
*/