CREATE TABLE AIRLINE (
	CODE INT not null,
	NAME VARCHAR(256),
	COUNTRY VARCHAR(256)
)

CREATE TABLE AIRPLANE (
	CODE INT not null,
	TYPE VARCHAR(256),
	SEATS INT,
	YEAR DATE
)

CREATE TABLE BOOKING (
	CODE INT not null,
	AGENCY VARCHAR(256),
	AIRLINE_CODE INT,
	FLIGHT_NUMBER INT,
	CUSTOMER_ID INT,
	BOOKING_DATE DATE,
	FLIGHT_DATE DATE,
	PRICE DECIMAL(6,2),
	STATUS VARCHAR(256)
)

CREATE TABLE AGENCY (
	NAME VARCHAR(256) not null,
	COUNTRY VARCHAR(256) not null,
	CITY VARCHAR(256),
	PHONE VARCHAR(10)
)

CREATE TABLE CUSTOMER (
	ID INT not null,
	FNAME VARCHAR(256),
	LNAME VARCHAR(256),
	EMAIL VARCHAR(256) 
)

CREATE TABLE FLIGHT (
	FNUMBER INT not null,
	AIRPLANE_OPERATOR INT,
	DEP_OPERATOR INT,
	ARR_AIRPORT INT,
	FLIGHT_TIME TIME,
	FLIGHT_DURATION INT,
	AIRPLANE INT
)

CREATE TABLE AIRPORT (
	CODE INT not null,
	NAME VARCHAR(256),
	COUNTRY VARCHAR(256),
	CITY VARCHAR(256)
)