USE master
GO
if exists (select * from sysdatabases where name='flights')
	DROP DATABASE flights
GO

CREATE DATABASE flights
GO
USE flights
GO

CREATE TABLE AIRLINE (
	CODE INT,
	NAME VARCHAR(256),
	COUNTRY VARCHAR(256)
)

CREATE TABLE AIRPLANE (
	CODE INT,
	TYPE VARCHAR(256),
	SEATS INT,
	YEAR DATE
)

CREATE TABLE BOOKING (
	CODE INT,
	AGENCY VARCHAR(256),
	AIRPLANE_CODE INT,
	FLIGHT_NUMBER INT,
	CUSTOMER_ID INT,
	BOOKING_DATE DATE,
	FLIGHT_DATE DATE,
	PRICE DECIMAL(6,2),
	STATUS VARCHAR(256)
)

CREATE TABLE AGENCY (
	NAME VARCHAR(256),
	COUNTRY VARCHAR(256),
	CITY VARCHAR(256),
	PHONE VARCHAR(10)
)

CREATE TABLE CUSTOMER (
	ID INT,
	FNAME VARCHAR(256),
	LNAME VARCHAR(256),
	EMAIL VARCHAR(256) 
)

CREATE TABLE FLIGHT (
	FNUMBER INT,
	AIRPLANE_OPERATOR INT,
	DEP_OPERATOR INT,
	ARR_AIRPORT INT,
	FLIGHT_TIME TIME,
	FLIGHT_DURATION INT,
	AIRPLANE INT
)

CREATE TABLE AIRPORT (
	CODE INT,
	NAME VARCHAR(256),
	COUNTRY VARCHAR(256),
	CITY VARCHAR(256)
)